### ISSUE TITLE
feat: support Python 3.x < 3.10

### ISSUE THREAD

**Issue by jace** [artisanofcode/python-zbase32#96]
This code currently requires Python 3.10 or later, but it can work with 3.7 (3.6?) or later with only a small change. This method…

```python
def _chunks(
    buffer: bytearray,
    size: int,
) -> collections.abc.Generator[bytearray, None, None]:
```

…can have return type changed to `-> typing.Generator[bytearray, None, None]:`. This will allow use in code that targets older versions of Python.

**Comment by danielknell** [comment]
The most i would probably consider loosening it would be to 3.8 as 3.7 is end-of-life next month.

I guess the library as is probably compatible with 3.9 already when `collections.abc` got generic support, its 3.10 mostly because i was too lazy to test older versions properly.

I would consider a PR to make it 3.8 compatible - with comments to make pylint stop moaning about the depreciation of the `typing` classes - but thats only got a little over a year left till its EOL.

what version are you hoping for?

**Comment by jace** [comment]
For my libraries I try to support the lowest possible version of Python, which currently is 3.7 as 3.6 doesn't support `from __future__ import annotations`. Supporting 3.8+ is reasonable.
